### ISSUE TITLE
Improve Action Error Message

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-stack#421]
For wrong codes, the webapp shows an error message like this

![image](https://user-images.githubusercontent.com/1026940/86792009-5696a100-c06a-11ea-889f-0a2e9921937f.png)

Unpack the error to make it nice. Try yourself: https://desec.io/confirm/renew-domain/invalid==/

**Comment by peterthomassen** [comment]
fixed in d2de2c61334744d2b356e6a209f0aba57ca5e0c0

**Comment by nils-wisiol** [comment]
Above [link](https://desec.io/confirm/renew-domain/invalid==/) still shows: 
![image](https://user-images.githubusercontent.com/1026940/108724536-b7a1b500-7525-11eb-91a8-fe7a55f71f22.png)

**Comment by peterthomassen** [comment]
> Above [link](https://desec.io/confirm/renew-domain/invalid==/) still shows

not anymore ;-) Not sure exactly when/where it was fixed.
